# Generated by Django 3.1.14 on 2022-08-26 14:59

from django.db import migrations
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220826_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=phone_field.models.PhoneField(default=django.utils.timezone.now, help_text='Phone number', max_length=31),
            preserve_default=False,
        ),
    ]
