# Generated by Django 3.1.14 on 2022-08-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
                ('first', models.CharField(max_length=250)),
                ('second', models.CharField(max_length=250)),
                ('third', models.CharField(max_length=250)),
                ('fourth', models.CharField(max_length=250)),
                ('option_one_count', models.IntegerField(default=0)),
                ('option_two_count', models.IntegerField(default=0)),
                ('option_three_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
