# Generated by Django 3.1.14 on 2022-08-26 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('poll', '0003_pollquestion_option_four_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollquestion',
            name='username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
